dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.2.0

compiler:
  solc:
    remapping:
      - '@chainlink=/Users/arik/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.2.0'

dotenv: .env
networks:
  default: ganache-local
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1FA494EC906CE90E9F37563A8AF630E'
    verify: False
  mainnet_fork_dev:
    eth_usd_price_feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}